import type { MenuItem } from './types'

export const STATIC_MENU_ITEMS: MenuItem[] = [
  {
    id: 'strawberry',
    category: 'smoothie',
    name_ja: '100%イチゴ',
    name_en: '100% Strawberry',
    price: 1700,
    description_ja: '完熟いちごを丸ごと使用した、甘みと酸味のバランスが絶妙なスムージー。',
    description_en: 'A perfectly balanced smoothie made with whole ripe strawberries.',
    image_url: '/images/menu/strawberry.jpg',
    active: true,
  },
  {
    id: 'mango',
    category: 'smoothie',
    name_ja: 'マンゴーヨーグルト',
    name_en: 'Mango Yogurt',
    price: 2200,
    description_ja: '南国の濃厚なマンゴーをたっぷり使用。とろけるような甘さをお楽しみください。',
    description_en: 'Rich and creamy smoothie made with generous amounts of tropical mango and yogurt.',
    image_url: '/images/menu/mango.jpg',
    active: true,
  },
  {
    id: 'melon',
    category: 'smoothie',
    name_ja: '100%メロン',
    name_en: '100% Melon',
    price: 1800,
    description_ja: '上品な甘みと香りが広がる、旬のメロンを使ったプレミアムスムージー。',
    description_en: 'A premium smoothie bursting with the elegant sweetness and aroma of seasonal melon.',
    image_url: '/images/menu/melon.jpg',
    active: true,
  },
  {
    id: 'mikan',
    category: 'smoothie',
    name_ja: '100%特選みかん',
    name_en: '100% Premium Mandarin',
    price: 1800,
    description_ja: '糖度の高い特選みかんをそのままスムージーに。濃厚な甘みが広がります。',
    description_en: 'A rich smoothie made from premium high-sugar mandarin oranges.',
    image_url: '/images/menu/orange.jpg',
    active: true,
  },
  {
    id: 'pineapple',
    category: 'smoothie',
    name_ja: 'パイナップルヨーグルト',
    name_en: 'Pineapple Yogurt',
    price: 1000,
    description_ja: 'トロピカルな甘みと爽やかな酸味が特徴のパイナップルスムージー。',
    description_en: 'Tropical sweetness with a refreshing tang — pineapple blended with yogurt.',
    image_url: '/images/menu/pineapple.jpg',
    active: true,
  },
  {
    id: 'blueberry',
    category: 'smoothie',
    name_ja: 'ブルーベリーヨーグルト',
    name_en: 'Blueberry Yogurt',
    price: 1500,
    description_ja: '濃厚な甘みと豊かな香りのブルーベリーを贅沢に使用したスムージー。',
    description_en: 'A rich, deeply flavored smoothie made with an abundance of fresh blueberries and yogurt.',
    image_url: '/images/menu/blueberry.jpg',
    active: true,
  },
  {
    id: 'watermelon',
    category: 'smoothie',
    name_ja: '100%スイカ',
    name_en: '100% Watermelon',
    price: 2000,
    description_ja: '夏を代表するスイカをたっぷり使用。みずみずしい甘さが口いっぱいに広がります。',
    description_en: 'Loaded with juicy watermelon — a refreshing taste of summer in every sip.',
    image_url: '/images/menu/watermelon.jpg',
    active: true,
  },
  {
    id: 'fig',
    category: 'smoothie',
    name_ja: 'イチジクヨーグルト',
    name_en: 'Fig Yogurt',
    price: 1800,
    description_ja: '上品な甘みが特徴の白いちじくを使った、季節限定スムージー。',
    description_en: 'A seasonal smoothie made with delicately sweet white figs and yogurt.',
    image_url: '/images/menu/fig.jpg',
    active: true,
  },
  {
    id: 'banana',
    category: 'smoothie',
    name_ja: 'バナナミルク',
    name_en: 'Banana Milk',
    price: 900,
    description_ja: '濃厚でクリーミーなバナナをそのままスムージーに。',
    description_en: 'Rich and creamy banana milk smoothie made with premium bananas.',
    image_url: '/images/menu/banana.jpg',
    active: true,
  },
  {
    id: 'banana-matcha',
    category: 'smoothie',
    name_ja: 'バナナミルク抹茶',
    name_en: 'Banana Milk Matcha',
    price: 1200,
    description_ja: 'クリーミーなバナナミルクと香り高い抹茶を合わせた、濃厚スムージー。',
    description_en: 'Creamy banana milk blended with rich matcha — a uniquely satisfying smoothie.',
    image_url: '/images/menu/banana_matcha.jpg',
    active: true,
  },
  {
    id: 'coconut',
    category: 'smoothie',
    name_ja: 'ココナッツ',
    name_en: 'Coconut',
    price: 1000,
    description_ja: 'トロピカルな甘みと香りのココナッツスムージー。',
    description_en: 'A tropical coconut smoothie with rich, natural sweetness.',
    image_url: '/images/menu/coconut.jpg',
    active: true,
  },
  {
    id: 'strawberry-softcream',
    category: 'fruit',
    name_ja: 'イチゴ＋ソフトクリーム',
    name_en: 'Strawberry + Soft Cream',
    price: 1500,
    description_ja: '完熟いちごのカットフルーツにソフトクリームを添えた贅沢な一品。',
    description_en: 'Ripe cut strawberries served with soft-serve ice cream.',
    image_url: '/images/menu/cut_strawberry.jpg',
    active: true,
    note_ja: '5月中旬まで',
    note_en: 'Until mid-May',
  },
  {
    id: 'melon-softcream',
    category: 'fruit',
    name_ja: 'メロン＋ソフトクリーム',
    name_en: 'Melon + Soft Cream',
    price: 1800,
    description_ja: '上品な甘みのメロンカットフルーツにソフトクリームを添えて。',
    description_en: 'Elegantly sweet cut melon served with soft-serve ice cream.',
    image_url: '/images/menu/cut_melon.jpg',
    active: true,
  },
  {
    id: 'mango-softcream',
    category: 'fruit',
    name_ja: 'マンゴー＋ソフトクリーム',
    name_en: 'Mango + Soft Cream',
    price: 2500,
    description_ja: '濃厚な南国マンゴーのカットフルーツにソフトクリームを合わせた特別な組み合わせ。',
    description_en: 'Rich tropical mango cut fruit paired with soft-serve ice cream.',
    image_url: '/images/menu/cut_mango.jpg',
    active: true,
  },
  {
    id: 'pineapple-softcream',
    category: 'fruit',
    name_ja: 'パイナップル＋ソフトクリーム',
    name_en: 'Pineapple + Soft Cream',
    price: 1200,
    description_ja: '爽やかなパイナップルのカットフルーツにソフトクリームを添えて。',
    description_en: 'Refreshing cut pineapple served with soft-serve ice cream.',
    image_url: '/images/menu/cut_pinapple.jpg',
    active: true,
  },
  {
    id: 'watermelon-softcream',
    category: 'fruit',
    name_ja: 'スイカ＋ソフトクリーム',
    name_en: 'Watermelon + Soft Cream',
    price: 1500,
    description_ja: 'みずみずしいスイカのカットフルーツにソフトクリームを添えて。',
    description_en: 'Juicy cut watermelon served with soft-serve ice cream.',
    image_url: '/images/menu/cut_watermelon.jpg',
    active: true,
  },
]
