import type { MenuItem } from './types'

export const STATIC_MENU_ITEMS: MenuItem[] = [
  {
    id: 'strawberry',
    category: 'smoothie',
    name_ja: '100%イチゴ',
    name_en: '100% Strawberry',
    price: 1700,
    description_ja: '契約農園でギリギリまで完熟させた朝採りイチゴを冷凍保存し、水、氷、シロップを一切使用せず、完熟ならではのコクと香りにこだわりました。濃厚な香り、爽やかな酸味、そして甘みをお楽しみください。',
    description_en: 'Freshly picked strawberries from our partner farm, frozen at peak ripeness. Made with zero water, ice, or syrup — pure strawberry richness, aroma, and sweetness.',
    image_url: '/images/menu/strawberry.jpg',
    active: true,
  },
  {
    id: 'mango',
    category: 'smoothie',
    name_ja: 'マンゴーヨーグルト',
    name_en: 'Mango Yogurt',
    price: 2200,
    description_ja: '香り、甘みが強い宮崎完熟マンゴーにこだわってます。ヨーグルトと合わせて喉越し良い仕上がりにしました。',
    description_en: 'We insist on fully ripe Miyazaki mango for its exceptional aroma and sweetness, blended with yogurt for a smooth, refreshing finish.',
    image_url: '/images/menu/mango.jpg',
    active: true,
  },
  {
    id: 'melon',
    category: 'smoothie',
    name_ja: '100%メロン',
    name_en: '100% Melon',
    price: 1800,
    description_ja: '旬の時期、いちばん美味しい地域で収穫されたメロンだけで丁寧に作るスムージーです。水、氷、シロップは一切使用せず、メロンそのものの甘さ、香り、口溶け感をお楽しみ下さい。',
    description_en: 'Made only with melon sourced from the best region at peak season. Zero water, ice, or syrup — just the pure sweetness, aroma, and melt-in-your-mouth texture of melon itself.',
    image_url: '/images/menu/melon.jpg',
    active: true,
  },
  {
    id: 'mikan',
    category: 'smoothie',
    name_ja: '100%特選みかん',
    name_en: '100% Premium Mandarin',
    price: 1800,
    description_ja: '契約農園でギリギリまで熟成させた高糖度のみかんを約10個使います。水、氷、シロップを一切使用せず、熟成ならではの香りにこだわりました。濃厚な香り、爽やかな酸味、そして甘みをお楽しみください。',
    description_en: 'About 10 high-sugar mandarins, ripened to the very limit at our partner farm. Made with zero water, ice, or syrup — pure aroma, refreshing acidity, and natural sweetness.',
    image_url: '/images/menu/orange.jpg',
    active: true,
  },
  {
    id: 'pineapple',
    category: 'smoothie',
    name_ja: 'パイナップルヨーグルト',
    name_en: 'Pineapple Yogurt',
    price: 1000,
    description_ja: 'トロピカルな甘みと爽やかな酸味が特徴のパイナップルスムージー。',
    description_en: 'Tropical sweetness with a refreshing tang — pineapple blended with yogurt.',
    image_url: '/images/menu/pineapple.jpg',
    active: true,
  },
  {
    id: 'blueberry',
    category: 'smoothie',
    name_ja: 'ブルーベリーヨーグルト',
    name_en: 'Blueberry Yogurt',
    price: 1500,
    description_ja: '濃厚な甘みと豊かな香りのブルーベリーを贅沢に使用したスムージー。',
    description_en: 'A rich, deeply flavored smoothie made with an abundance of fresh blueberries and yogurt.',
    image_url: '/images/menu/blueberry.jpg',
    active: true,
  },
  {
    id: 'watermelon',
    category: 'smoothie',
    name_ja: '100%スイカ',
    name_en: '100% Watermelon',
    price: 2000,
    description_ja: '糖度センサーで甘みの強い個体を選別し、赤みの強いスイカを冷凍。作る直前にカットした生スイカと合わせた瑞々しいスムージーです。',
    description_en: 'Selected by sugar sensor for maximum sweetness, then frozen. Blended with fresh-cut watermelon just before serving for the most vibrant, juicy smoothie.',
    image_url: '/images/menu/watermelon.jpg',
    active: true,
  },
  {
    id: 'fig',
    category: 'smoothie',
    name_ja: 'イチジクヨーグルト',
    name_en: 'Fig Yogurt',
    price: 1800,
    description_ja: '契約農園で収穫される無農薬の白イチジク（バナーネ）を完熟冷凍し、ヨーグルトドリンクとミルクを加えました。上品な甘みと濃厚な風味をお楽しみください。',
    description_en: 'Pesticide-free white figs (Banane variety) from our partner farm, frozen at peak ripeness, blended with yogurt drink and milk. Elegant sweetness with a rich, full flavour.',
    image_url: '/images/menu/fig.jpg',
    active: true,
  },
  {
    id: 'banana',
    category: 'smoothie',
    name_ja: 'バナナミルク',
    name_en: 'Banana Milk',
    price: 900,
    description_ja: 'フィリピン高地栽培のバナナを熟成させ冷凍。ミルクを加えただけですが、バナナだけの上品な甘みと濃厚な香りをご堪能ください。',
    description_en: 'Highland-grown Philippine bananas, ripened and frozen at their peak, blended simply with milk. Let the pure, elegant sweetness and rich aroma of banana speak for itself.',
    image_url: '/images/menu/banana.jpg',
    active: true,
  },
  {
    id: 'banana-matcha',
    category: 'smoothie',
    name_ja: 'バナナミルク抹茶',
    name_en: 'Banana Milk Matcha',
    price: 1200,
    description_ja: 'クリーミーなバナナミルクと香り高い抹茶を合わせた、濃厚スムージー。',
    description_en: 'Creamy banana milk blended with rich matcha — a uniquely satisfying smoothie.',
    image_url: '/images/menu/banana_matcha.jpg',
    active: true,
  },
  {
    id: 'coconut',
    category: 'smoothie',
    name_ja: 'ココナッツ',
    name_en: 'Coconut',
    price: 1000,
    description_ja: 'トロピカルな甘みと香りのココナッツスムージー。',
    description_en: 'A tropical coconut smoothie with rich, natural sweetness.',
    image_url: '/images/menu/coconut.jpg',
    active: true,
  },
  {
    id: 'strawberry-softcream',
    category: 'fruit',
    name_ja: 'イチゴ＋ソフトクリーム',
    name_en: 'Strawberry + Soft Cream',
    price: 1500,
    description_ja: '完熟いちごのカットフルーツにソフトクリームを添えた贅沢な一品。',
    description_en: 'Ripe cut strawberries served with soft-serve ice cream.',
    image_url: '/images/menu/cut_strawberry.jpg',
    active: true,
    note_ja: '5月中旬まで',
    note_en: 'Until mid-May',
  },
  {
    id: 'melon-softcream',
    category: 'fruit',
    name_ja: 'メロン＋ソフトクリーム',
    name_en: 'Melon + Soft Cream',
    price: 1800,
    description_ja: '上品な甘みのメロンカットフルーツにソフトクリームを添えて。',
    description_en: 'Elegantly sweet cut melon served with soft-serve ice cream.',
    image_url: '/images/menu/cut_melon.jpg',
    active: true,
  },
  {
    id: 'mango-softcream',
    category: 'fruit',
    name_ja: 'マンゴー＋ソフトクリーム',
    name_en: 'Mango + Soft Cream',
    price: 2500,
    description_ja: '濃厚な南国マンゴーのカットフルーツにソフトクリームを合わせた特別な組み合わせ。',
    description_en: 'Rich tropical mango cut fruit paired with soft-serve ice cream.',
    image_url: '/images/menu/cut_mango.jpg',
    active: true,
  },
  {
    id: 'pineapple-softcream',
    category: 'fruit',
    name_ja: 'パイナップル＋ソフトクリーム',
    name_en: 'Pineapple + Soft Cream',
    price: 1200,
    description_ja: '爽やかなパイナップルのカットフルーツにソフトクリームを添えて。',
    description_en: 'Refreshing cut pineapple served with soft-serve ice cream.',
    image_url: '/images/menu/cut_pinapple.jpg',
    active: true,
  },
  {
    id: 'watermelon-softcream',
    category: 'fruit',
    name_ja: 'スイカ＋ソフトクリーム',
    name_en: 'Watermelon + Soft Cream',
    price: 1500,
    description_ja: 'みずみずしいスイカのカットフルーツにソフトクリームを添えて。',
    description_en: 'Juicy cut watermelon served with soft-serve ice cream.',
    image_url: '/images/menu/cut_watermelon.jpg',
    active: true,
  },
]
