name = "bella-frutta-web"
main = ".open-next/worker.js"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "bella-frutta.jp/*", custom_domain = true },
  { pattern = "www.bella-frutta.jp/*", custom_domain = true }
]

[assets]
directory = ".open-next/assets"

[vars]
NEXT_PUBLIC_ENV = "production"
